[package]
name = "client"
version = "0.1.0"
authors = ["Alexander <krikun.contact@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.3.12"